name = "checkmark"
version = "3.0.1"

description = "Gleam markdown snippet validator"
licences = ["Apache-2.0"]
repository = { type = "github", user = "sbergen", repo = "checkmark" }
internal_modules = ["checkmark/internal/*"]

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
splitter = ">= 1.0.0 and < 2.0.0"
glance = ">= 6.0.0 and < 7.0.0"
tom = ">= 2.0.0 and < 3.0.0"
simplifile = ">= 2.2.0 and < 3.0.0"
iv = ">= 1.4.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
gleam_erlang = ">= 1.2.0 and < 2.0.0"
envoy = ">= 1.0.2 and < 2.0.0"
